export const timelineElement = [
    {
        id:1,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "2023",
        icon: "MdTimeline",
    },
    {
        id:2,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "2020",
        icon: "MdTimeline",
    },
    {
        id:3,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "2018",
        icon: "MdTimeline",
    },
    {
        id:4,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "2005",
        icon: "MdFace",
    },
    {
        id:5,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "2000",
        icon: "MdFace",
    },
    {
        id:6,
        title: "Lorem ipsum",
        location: "Lorem ipsum",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        buttonText: "View Project",
        date: "1998",
        icon: "MdFace",
    },
]

